import streamlit as st
from PIL import Image
import torch

st.set_page_config(page_title="Image Caption Generator", layout="centered")
st.title("🖼️ AI-Powered Image Caption Generator")
st.write("Upload an image and receive a descriptive caption generated by AI.")

# Dummy placeholder for model loading (replace with your actual model)
@st.cache_resource
def load_model():
    # Example: load a trained PyTorch model
    # model = torch.load("src/model.pth", map_location="cpu")
    # model.eval()
    # return model
    return None

model = load_model()

def generate_caption(image):
    # TODO: Replace with your actual image captioning logic
    return "A placeholder caption describing the uploaded image."

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_column_width=True)
    st.write("Generating caption...")
    caption = generate_caption(image)
    st.success(f"**Caption:** {caption}")

st.markdown("---")
st.markdown("**Note:** Replace the `generate_caption` function with your trained model for real predictions.")